spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel
    username: root
    password: 1538
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
server:
  port: 8082
 