spring:
  datasource:
    url: jdbc:mysql://localhost:3306/item_service_microservices
    username: root
    password: 1538
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: item-service
server:
 port: 8081